### ISSUE TITLE
Webpack build failing - "define cannot be used indirect"

### ISSUE THREAD

**Issue by halhenke** [reverentgeek/reactor#1]
When trying to build/run the app according to the README instructions I was running into the foolowing error: [https://github.com/webpack/webpack/issues/138](https://github.com/webpack/webpack/issues/138)

A temp solution is given in [https://github.com/webpack/webpack/issues/138#issuecomment-160638284](https://github.com/webpack/webpack/issues/138#issuecomment-160638284).

So the following in `webpack/make-webpack-config.js` fixes this for now:

```
module: {
    ...
    noParse: /node_modules\/json-schema\/lib\/validate\.js/
},
```

**Comment by reverentgeek** [comment]
Yeah, it's been a while since I've worked on this, and I'm sure it's gotten a bit rusty. Thanks for contributing a fix!
