### ISSUE TITLE
Can't install reactor on windows..

### ISSUE THREAD

**Issue by clockwisemusic** [reverentgeek/reactor#3]
I don't know much/anything about Node so I'm probably doing it wrong... but after downloading your app and typing "npm install" I get this:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.10
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by reverentgeek** [comment]
It sounds like you might not have the build tools needed to compile some of the dependencies. What OS are you running on?

**Comment by reverentgeek** [comment]
Doh! Sorry... just saw that you're on Windows. Try installing [Python 2.x](https://www.python.org/downloads/windows/) and the [Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools).

**Comment by reverentgeek** [comment]
When installing Python, make sure it's version 2.x (e.g. 2.7), and that it adds it to your PATH.

**Comment by reverentgeek** [comment]
Oh, and you'll need to close and relaunch the console window after you install both of those, so that it picks up on the changes to your PATH. Hope this helps!

**Comment by bryanj4** [comment]
Is there a specific version of node that you use?

**Comment by reverentgeek** [comment]
@bryanj4 I believe I was using some version of 4.x when I originally created this app. I really need to recreate this in the latest versions of everything. I'll try to do that within the next couple of days.

**Comment by reverentgeek** [comment]
With the latest commit, you can now run and build on Windows.
